projects:
  bgdbv3amplify:
    schemaPath: src/graphql/schema.json
    includes:
      - aws-export.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
